// Next.js App Router Components for whetstone-cyber.in
// Optimized for Core Web Vitals (LCP < 2.5s, CLS < 0.1, INP < 200ms)
// Generated by ExtractDesign Studio

import React from 'react';
import Image from 'next/image';

'use client';
export function Button({ children, variant = 'primary', className = '', ...props }) {
  const styles = {
    primary: { backgroundColor: 'var(--color-brand-primary, #ffffff)', color: '#fff', border: 'none', padding: '10px 20px', borderRadius: '8px', fontWeight: 600, cursor: 'pointer' },
    secondary: { backgroundColor: 'transparent', border: '1px solid rgba(128,128,128,0.3)', padding: '10px 20px', borderRadius: '8px', fontWeight: 600, cursor: 'pointer' },
  };
  return <button style={styles[variant]} className={className} {...props}>{children}</button>;
}

export function Hero({ headline, description, ctaText = 'Get Started', imageSrc }) {
  return (
    <section style={{ padding: '64px 24px', textAlign: 'center', maxWidth: '960px', margin: '0 auto' }}>
      <h1 style={{ fontSize: '42px', fontWeight: 700, marginBottom: '16px' }}>{headline}</h1>
      <p style={{ fontSize: '18px', opacity: 0.8, marginBottom: '28px' }}>{description}</p>
      {imageSrc && <Image src={imageSrc} alt={headline} width={800} height={450} priority />}
      <Button>{ctaText}</Button>
    </section>
  );
}
