// theme.ts — pitowings.com
// Auto-generated by ExtractDesign Studio
// Import and use in _app.tsx, layout.tsx, or ThemeProvider

export const theme = {
  colors: {
  surface_base: '#1b1418',
  feedback_danger: '#a50d26',
  text_muted: '#c8102e',
  red: '#e11d3f',
  brand_secondary: '#f65a76',
  purple: '#a999aa',
  brand_primary: '#ff9aab',
  text_subtle: '#ffc6cf',
  brand_accent: '#ffe0e4',
  text_on_dark: '#ffffff',
  },
  fonts: {
  sans: '"Poppins",ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif',
  mono: 'ui-monospace,SFMono-Regular,"SF Mono",Menlo,Consolas,"Liberation Mono","Courier New",monospace',
  },
  borderRadius: {
    sm: '0',
    md: '.25rem',
    lg: '.5rem',
    full: '9999px',
  },
} as const;

export type ThemeColors = keyof typeof theme.colors;
export type ThemeFonts = keyof typeof theme.fonts;
